version: '3.8'

services:
  web:
    image: ghcr.io/felix-orduz/misw4204-web:latest
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgrespwd@db:5432/conversor
      SAVE_PATH: /file_conversor/uploaded/
      SERVER_URI: http://localhost:5001/
      CONVERT_PATH: /file_conversor/processed/
    depends_on:
      - db
    volumes:
      - "$HOME/file_conversor/uploaded/:/file_conversor/uploaded/"
      - "$HOME/file_conversor/processed/:/file_conversor/processed/"

  db:
    image: postgres:alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: conversor
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  batch_processor :
    image: ghcr.io/felix-orduz/misw4204-batch:latest
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:postgrespwd@db:5432/conversor
    depends_on:
      - web
      - redis
      - db

  worker :
    image: ghcr.io/felix-orduz/misw4204-worker:latest
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:postgrespwd@db:5432/conversor
      SAVE_PATH: /file_conversor/uploaded/
      CONVERT_PATH: /file_conversor/processed/
    depends_on:
      - web
      - redis
      - db
      - batch_processor
    volumes:
      - "$HOME/file_conversor/uploaded/:/file_conversor/uploaded/"
      - "$HOME/file_conversor/processed/:/file_conversor/processed/"

volumes:
  postgres_data:

